### ISSUE TITLE
Warning that should be removed

### ISSUE THREAD

**Issue by TomasArce** [tcbrindle/span#18]
TCB_SPAN_INLINE_VAR constexpr std::size_t dynamic_extent = -1;

should be:

TCB_SPAN_INLINE_VAR constexpr std::size_t dynamic_extent = ~std::size_t(0);

**Comment by brandl-muc** [comment]
With MSVC with warning level 4 this leads to the following:
`warning C4245: 'initializing': conversion from 'int' to 'size_t', signed/unsigned mismatch`
Also see [this online example](https://rextester.com/FRU86770).

We compile with /W4 and warnings as errors, so we can't use span out of the box. (thanks for the work btw)

Although there don't seem to be any implementations that don't use two's complement and there are afaik ideas to make the abstract machine two's compement currently using `-1` is non-compliant. Same goes for `~0` of course.
I'd propose using `SIZE_MAX` or in case you don't want to add the extra header `std::size_t{} - 1u` should also work because [modular arithmetics are guaranteed for unsigned types](https://stackoverflow.com/a/7221449/1969455).
