### ISSUE TITLE
A couple codacy (cppcheck) issues.

### ISSUE THREAD

**Issue by p-groarke** [tcbrindle/span#22]
Just a FYI. Codacy reports some minor issues.

Constructors with single arguments that aren't marked `explicit`.

struct member 'is_container::value' is never used.

Good day

**Comment by tcbrindle** [comment]
Hi @p-groarke,

> Constructors with single arguments that aren't marked explicit.

We aim to follow the C++20 specification of `span`, which does mark its constructors as explicit. In any case, I'm not sure I understand the nature of the complaint: it seems to me that implicit conversion of, say, `vector<int>` to `span<int>` in a function argument is exactly what is intended by the design.

> struct member 'is_container::value' is never used.

It's used in the SFINAE constraints of the two "from container" constructors, [here](https://github.com/tcbrindle/span/blob/master/include/tcb/span.hpp#L359) and [here](https://github.com/tcbrindle/span/blob/master/include/tcb/span.hpp#L370). Perhaps this is triggering because the value is only used at compile time, not at run time?

I'm going to close this as these do not seem to be valid bugs in this case, but feel free to reopen if there is something obvious I've missed.
