### ISSUE TITLE
Support for construction using std::initializer_list<T>

### ISSUE THREAD

**Issue by kammce** [tcbrindle/span#23]
In a lot of my projects I tend to use initializer lists as a shorthand over creating an array object and constructing a span from that. For example:
```
#include <cstdio>
#include <span>

void UseSpan(std::span<const char> str)
{
    printf("%s\n", str.data());
}

int main() {
  const char arr[] = { 'a', 'b', 'c', 'd', '\0'};
  UseSpan(arr);
  // Error: '<brace-enclosed initializer list>' to 
  //        'std::span<const char>'
  // UseSpan({ 'a', 'b', 'c', 'd', '\0'});  
  return 0;
}
```
https://godbolt.org/z/tMKbYF

The example is esoteric, but it demonstrates the desired effect. Any particular reason why the span library could not have construction from init lists available to it as well?

It is is something that is desirable, I've made a change on my fork to add support for this that I can make a PR for.

**Comment by tcbrindle** [comment]
Hi, thanks for the suggestion!

This implementation of `span` aims to follow the C++20 proposal as closely as possible, in order to make it easy for people to switch to `std::span` when they upgrade to '20 (the `make_span()` functions are  a temporary workaround for the lack of CTAD before '17).  C++20's `span` doesn't provide a separate constructor or deduction guide for `std::initializer_list`, so I'm reluctant to add them here I'm afraid.
